GSoares\Hydroponics\Domain\Entity\Crop:
  type: entity
  repositoryClass: GSoares\Hydroponics\Domain\Repository\Crop\CropRepository
  table: Crop
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 250
      column: name
      nullable: false
    quantity:
      type: integer
      column: quantity
      nullable: false
    quantityHarvested:
      type: integer
      column: quantity_harvested
      nullable: true
    quantityLost:
      type: integer
      column: quantity_lost
      nullable: true
    harvestedAt:
      type: datetime
      column: harvested_at
      nullable: true
    createdAt:
      type: datetime
      column: created_at
      nullable: false
    updatedAt:
      type: datetime
      column: updated_at
      nullable: true
    deletedAt:
      type: datetime
      column: deleted_at
      nullable: true
  manyToOne:
    plant:
      targetEntity: GSoares\Hydroponics\Domain\Entity\Plant
      joinColumn:
        name: plant_id
        referencedColumnName: id
        nullable: false
    system:
      targetEntity: GSoares\Hydroponics\Domain\Entity\System
      joinColumn:
        name: system_id
        referencedColumnName: id
        nullable: false